---
title: "Count Data, Poisson regression"
author: "Hana Akbarnejad"
date: "3/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)
library(ggplot2)
library(readr)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r data_import}

crab_data = read_table2("HW5-crab.txt") %>% 
  janitor::clean_names()
```

### 1-a
Fit a Poisson model (M1) with log link with W(carapace width) as the single predictor. Check the goodness of fit and interpret your model.
```{r poi_w}

# fir poisson model
m1 = glm(sa ~ w, family=poisson(link = "log"), data=crab_data)
summary(m1)

# gof
deviance_m1 = m1$deviance
df_m1 =  m1$df.residual             # df=n-p
pval=1-pchisq(deviance_m1,df=df_m1) # chisq test
pval                                # pvalue is 0 this shows that the fit is not good
```

interpretation:

### 1-b
Fit a model (M2) with W and Wt as predictors. Compare it with the model in (a). Interpret your results.
```{r poi_w_wt}

```

